<?php
/**
 * OrganisationApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HelloAsso API
 *
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * OrganisationApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganisationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'organizationsLegalInformationsLegalStructuresGet' => [
            'application/json',
        ],
        'organizationsLegalInformationsOrganizationSlugConfigurationGet' => [
            'application/json',
        ],
        'organizationsLegalInformationsOrganizationSlugConfigurationPut' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'organizationsLegalInformationsTaxInformationTextsGet' => [
            'application/json',
        ],
        'organizationsOrganizationSlugGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation organizationsLegalInformationsLegalStructuresGet
     *
     * Obtenir la structure juridique d&#39;une organisation visible.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsLegalStructuresGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[]
     */
    public function organizationsLegalInformationsLegalStructuresGet(string $contentType = self::contentTypes['organizationsLegalInformationsLegalStructuresGet'][0])
    {
        list($response) = $this->organizationsLegalInformationsLegalStructuresGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation organizationsLegalInformationsLegalStructuresGetWithHttpInfo
     *
     * Obtenir la structure juridique d&#39;une organisation visible.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsLegalStructuresGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsLegalInformationsLegalStructuresGetWithHttpInfo(string $contentType = self::contentTypes['organizationsLegalInformationsLegalStructuresGet'][0])
    {
        $request = $this->organizationsLegalInformationsLegalStructuresGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsLegalInformationsLegalStructuresGetAsync
     *
     * Obtenir la structure juridique d&#39;une organisation visible.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsLegalStructuresGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsLegalStructuresGetAsync(string $contentType = self::contentTypes['organizationsLegalInformationsLegalStructuresGet'][0])
    {
        return $this->organizationsLegalInformationsLegalStructuresGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsLegalInformationsLegalStructuresGetAsyncWithHttpInfo
     *
     * Obtenir la structure juridique d&#39;une organisation visible.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsLegalStructuresGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsLegalStructuresGetAsyncWithHttpInfo(string $contentType = self::contentTypes['organizationsLegalInformationsLegalStructuresGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel[]';
        $request = $this->organizationsLegalInformationsLegalStructuresGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsLegalInformationsLegalStructuresGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsLegalStructuresGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsLegalInformationsLegalStructuresGetRequest(string $contentType = self::contentTypes['organizationsLegalInformationsLegalStructuresGet'][0])
    {


        $resourcePath = '/organizations/legal-informations/legal-structures';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationGet
     *
     * Obtenir la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug organization_slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationGet($organization_slug, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'][0])
    {
        list($response) = $this->organizationsLegalInformationsOrganizationSlugConfigurationGetWithHttpInfo($organization_slug, $contentType);
        return $response;
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationGetWithHttpInfo
     *
     * Obtenir la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationGetWithHttpInfo($organization_slug, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'][0])
    {
        $request = $this->organizationsLegalInformationsOrganizationSlugConfigurationGetRequest($organization_slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationGetAsync
     *
     * Obtenir la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationGetAsync($organization_slug, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'][0])
    {
        return $this->organizationsLegalInformationsOrganizationSlugConfigurationGetAsyncWithHttpInfo($organization_slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationGetAsyncWithHttpInfo
     *
     * Obtenir la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationGetAsyncWithHttpInfo($organization_slug, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration';
        $request = $this->organizationsLegalInformationsOrganizationSlugConfigurationGetRequest($organization_slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsLegalInformationsOrganizationSlugConfigurationGet'
     *
     * @param  string $organization_slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationGetRequest($organization_slug, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationGet'][0])
    {

        // verify the required parameter 'organization_slug' is set
        if ($organization_slug === null || (is_array($organization_slug) && count($organization_slug) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_slug when calling organizationsLegalInformationsOrganizationSlugConfigurationGet'
            );
        }


        $resourcePath = '/organizations/legal-informations/{organizationSlug}/configuration';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization_slug !== null) {
            $resourcePath = str_replace(
                '{' . 'organizationSlug' . '}',
                ObjectSerializer::toPathValue($organization_slug),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationPut
     *
     * Mettre à jour la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug organization_slug (required)
     * @param  \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsUpdateOrganizationLegalInformationConfigurationBody|null $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationPut($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body = null, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'][0])
    {
        $this->organizationsLegalInformationsOrganizationSlugConfigurationPutWithHttpInfo($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body, $contentType);
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationPutWithHttpInfo
     *
     * Mettre à jour la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsUpdateOrganizationLegalInformationConfigurationBody|null $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationPutWithHttpInfo($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body = null, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'][0])
    {
        $request = $this->organizationsLegalInformationsOrganizationSlugConfigurationPutRequest($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationPutAsync
     *
     * Mettre à jour la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsUpdateOrganizationLegalInformationConfigurationBody|null $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationPutAsync($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body = null, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'][0])
    {
        return $this->organizationsLegalInformationsOrganizationSlugConfigurationPutAsyncWithHttpInfo($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsLegalInformationsOrganizationSlugConfigurationPutAsyncWithHttpInfo
     *
     * Mettre à jour la configuration des informations juridiques de l&#39;organisation.
     *
     * @param  string $organization_slug (required)
     * @param  \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsUpdateOrganizationLegalInformationConfigurationBody|null $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationPutAsyncWithHttpInfo($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body = null, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'][0])
    {
        $returnType = '';
        $request = $this->organizationsLegalInformationsOrganizationSlugConfigurationPutRequest($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsLegalInformationsOrganizationSlugConfigurationPut'
     *
     * @param  string $organization_slug (required)
     * @param  \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationLegalInformationsUpdateOrganizationLegalInformationConfigurationBody|null $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsLegalInformationsOrganizationSlugConfigurationPutRequest($organization_slug, $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body = null, string $contentType = self::contentTypes['organizationsLegalInformationsOrganizationSlugConfigurationPut'][0])
    {

        // verify the required parameter 'organization_slug' is set
        if ($organization_slug === null || (is_array($organization_slug) && count($organization_slug) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_slug when calling organizationsLegalInformationsOrganizationSlugConfigurationPut'
            );
        }



        $resourcePath = '/organizations/legal-informations/{organizationSlug}/configuration';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization_slug !== null) {
            $resourcePath = str_replace(
                '{' . 'organizationSlug' . '}',
                ObjectSerializer::toPathValue($organization_slug),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body));
            } else {
                $httpBody = $hello_asso_api_v5_models_organization_legal_informations_update_organization_legal_information_configuration_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsLegalInformationsTaxInformationTextsGet
     *
     * Obtenir les textes d&#39;information fiscale de l&#39;organisation.
     *
     * @param  string|null $organization_slug organization_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[]
     */
    public function organizationsLegalInformationsTaxInformationTextsGet($organization_slug = null, string $contentType = self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'][0])
    {
        list($response) = $this->organizationsLegalInformationsTaxInformationTextsGetWithHttpInfo($organization_slug, $contentType);
        return $response;
    }

    /**
     * Operation organizationsLegalInformationsTaxInformationTextsGetWithHttpInfo
     *
     * Obtenir les textes d&#39;information fiscale de l&#39;organisation.
     *
     * @param  string|null $organization_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[], HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsLegalInformationsTaxInformationTextsGetWithHttpInfo($organization_slug = null, string $contentType = self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'][0])
    {
        $request = $this->organizationsLegalInformationsTaxInformationTextsGetRequest($organization_slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsLegalInformationsTaxInformationTextsGetAsync
     *
     * Obtenir les textes d&#39;information fiscale de l&#39;organisation.
     *
     * @param  string|null $organization_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsTaxInformationTextsGetAsync($organization_slug = null, string $contentType = self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'][0])
    {
        return $this->organizationsLegalInformationsTaxInformationTextsGetAsyncWithHttpInfo($organization_slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsLegalInformationsTaxInformationTextsGetAsyncWithHttpInfo
     *
     * Obtenir les textes d&#39;information fiscale de l&#39;organisation.
     *
     * @param  string|null $organization_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsLegalInformationsTaxInformationTextsGetAsyncWithHttpInfo($organization_slug = null, string $contentType = self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText[]';
        $request = $this->organizationsLegalInformationsTaxInformationTextsGetRequest($organization_slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsLegalInformationsTaxInformationTextsGet'
     *
     * @param  string|null $organization_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsLegalInformationsTaxInformationTextsGetRequest($organization_slug = null, string $contentType = self::contentTypes['organizationsLegalInformationsTaxInformationTextsGet'][0])
    {



        $resourcePath = '/organizations/legal-informations/tax-information-texts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $organization_slug,
            'organizationSlug', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation organizationsOrganizationSlugGet
     *
     * Obtenir le détail d&#39;une organisation
     *
     * @param  string $organization_slug The organization Slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsOrganizationSlugGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel
     */
    public function organizationsOrganizationSlugGet($organization_slug, string $contentType = self::contentTypes['organizationsOrganizationSlugGet'][0])
    {
        list($response) = $this->organizationsOrganizationSlugGetWithHttpInfo($organization_slug, $contentType);
        return $response;
    }

    /**
     * Operation organizationsOrganizationSlugGetWithHttpInfo
     *
     * Obtenir le détail d&#39;une organisation
     *
     * @param  string $organization_slug The organization Slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsOrganizationSlugGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function organizationsOrganizationSlugGetWithHttpInfo($organization_slug, string $contentType = self::contentTypes['organizationsOrganizationSlugGet'][0])
    {
        $request = $this->organizationsOrganizationSlugGetRequest($organization_slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation organizationsOrganizationSlugGetAsync
     *
     * Obtenir le détail d&#39;une organisation
     *
     * @param  string $organization_slug The organization Slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsOrganizationSlugGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsOrganizationSlugGetAsync($organization_slug, string $contentType = self::contentTypes['organizationsOrganizationSlugGet'][0])
    {
        return $this->organizationsOrganizationSlugGetAsyncWithHttpInfo($organization_slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation organizationsOrganizationSlugGetAsyncWithHttpInfo
     *
     * Obtenir le détail d&#39;une organisation
     *
     * @param  string $organization_slug The organization Slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsOrganizationSlugGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function organizationsOrganizationSlugGetAsyncWithHttpInfo($organization_slug, string $contentType = self::contentTypes['organizationsOrganizationSlugGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\HelloAssoApiV5ModelsOrganizationOrganizationModel';
        $request = $this->organizationsOrganizationSlugGetRequest($organization_slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'organizationsOrganizationSlugGet'
     *
     * @param  string $organization_slug The organization Slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['organizationsOrganizationSlugGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function organizationsOrganizationSlugGetRequest($organization_slug, string $contentType = self::contentTypes['organizationsOrganizationSlugGet'][0])
    {

        // verify the required parameter 'organization_slug' is set
        if ($organization_slug === null || (is_array($organization_slug) && count($organization_slug) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_slug when calling organizationsOrganizationSlugGet'
            );
        }


        $resourcePath = '/organizations/{organizationSlug}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($organization_slug !== null) {
            $resourcePath = str_replace(
                '{' . 'organizationSlug' . '}',
                ObjectSerializer::toPathValue($organization_slug),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
