<?php
/**
 * HelloAssoApiV5ModelsStatisticsItemPayment
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HelloAsso API
 *
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * HelloAssoApiV5ModelsStatisticsItemPayment Class Doc Comment
 *
 * @category Class
 * @description Payment linked to the item
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HelloAssoApiV5ModelsStatisticsItemPayment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'HelloAsso.Api.V5.Models.Statistics.ItemPayment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cash_out_state' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentCashOutState',
        'share_amount' => 'int',
        'id' => 'int',
        'amount' => 'int',
        'amount_tip' => 'int',
        'date' => '\DateTime',
        'payment_means' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans',
        'installment_number' => 'int',
        'state' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentState',
        'type' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentType',
        'meta' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsCommonMetaModel',
        'payment_off_line_mean' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans',
        'refund_operations' => '\OpenAPI\Client\Model\HelloAssoApiV5ModelsStatisticsRefundOperationLightModel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cash_out_state' => null,
        'share_amount' => 'int32',
        'id' => 'int32',
        'amount' => 'int32',
        'amount_tip' => 'int32',
        'date' => 'date-time',
        'payment_means' => null,
        'installment_number' => 'int32',
        'state' => null,
        'type' => null,
        'meta' => null,
        'payment_off_line_mean' => null,
        'refund_operations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cash_out_state' => false,
        'share_amount' => false,
        'id' => false,
        'amount' => false,
        'amount_tip' => true,
        'date' => false,
        'payment_means' => false,
        'installment_number' => true,
        'state' => false,
        'type' => false,
        'meta' => false,
        'payment_off_line_mean' => false,
        'refund_operations' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cash_out_state' => 'cashOutState',
        'share_amount' => 'shareAmount',
        'id' => 'id',
        'amount' => 'amount',
        'amount_tip' => 'amountTip',
        'date' => 'date',
        'payment_means' => 'paymentMeans',
        'installment_number' => 'installmentNumber',
        'state' => 'state',
        'type' => 'type',
        'meta' => 'meta',
        'payment_off_line_mean' => 'paymentOffLineMean',
        'refund_operations' => 'refundOperations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cash_out_state' => 'setCashOutState',
        'share_amount' => 'setShareAmount',
        'id' => 'setId',
        'amount' => 'setAmount',
        'amount_tip' => 'setAmountTip',
        'date' => 'setDate',
        'payment_means' => 'setPaymentMeans',
        'installment_number' => 'setInstallmentNumber',
        'state' => 'setState',
        'type' => 'setType',
        'meta' => 'setMeta',
        'payment_off_line_mean' => 'setPaymentOffLineMean',
        'refund_operations' => 'setRefundOperations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cash_out_state' => 'getCashOutState',
        'share_amount' => 'getShareAmount',
        'id' => 'getId',
        'amount' => 'getAmount',
        'amount_tip' => 'getAmountTip',
        'date' => 'getDate',
        'payment_means' => 'getPaymentMeans',
        'installment_number' => 'getInstallmentNumber',
        'state' => 'getState',
        'type' => 'getType',
        'meta' => 'getMeta',
        'payment_off_line_mean' => 'getPaymentOffLineMean',
        'refund_operations' => 'getRefundOperations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cash_out_state', $data ?? [], null);
        $this->setIfExists('share_amount', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('amount_tip', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('payment_means', $data ?? [], null);
        $this->setIfExists('installment_number', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('payment_off_line_mean', $data ?? [], null);
        $this->setIfExists('refund_operations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cash_out_state
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentCashOutState|null
     */
    public function getCashOutState()
    {
        return $this->container['cash_out_state'];
    }

    /**
     * Sets cash_out_state
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentCashOutState|null $cash_out_state cash_out_state
     *
     * @return self
     */
    public function setCashOutState($cash_out_state)
    {
        if (is_null($cash_out_state)) {
            throw new \InvalidArgumentException('non-nullable cash_out_state cannot be null');
        }
        $this->container['cash_out_state'] = $cash_out_state;

        return $this;
    }

    /**
     * Gets share_amount
     *
     * @return int|null
     */
    public function getShareAmount()
    {
        return $this->container['share_amount'];
    }

    /**
     * Sets share_amount
     *
     * @param int|null $share_amount Amount of the item and extra options payed on this payment term (in cents)
     *
     * @return self
     */
    public function setShareAmount($share_amount)
    {
        if (is_null($share_amount)) {
            throw new \InvalidArgumentException('non-nullable share_amount cannot be null');
        }
        $this->container['share_amount'] = $share_amount;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The ID of the payment
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int|null $amount Total Amount of the payment (in cents)
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets amount_tip
     *
     * @return int|null
     */
    public function getAmountTip()
    {
        return $this->container['amount_tip'];
    }

    /**
     * Sets amount_tip
     *
     * @param int|null $amount_tip Tip Amount of the payment (in cents)
     *
     * @return self
     */
    public function setAmountTip($amount_tip)
    {
        if (is_null($amount_tip)) {
            array_push($this->openAPINullablesSetToNull, 'amount_tip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('amount_tip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['amount_tip'] = $amount_tip;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \DateTime|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime|null $date Date of the payment
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets payment_means
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans|null
     */
    public function getPaymentMeans()
    {
        return $this->container['payment_means'];
    }

    /**
     * Sets payment_means
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans|null $payment_means payment_means
     *
     * @return self
     */
    public function setPaymentMeans($payment_means)
    {
        if (is_null($payment_means)) {
            throw new \InvalidArgumentException('non-nullable payment_means cannot be null');
        }
        $this->container['payment_means'] = $payment_means;

        return $this;
    }

    /**
     * Gets installment_number
     *
     * @return int|null
     */
    public function getInstallmentNumber()
    {
        return $this->container['installment_number'];
    }

    /**
     * Sets installment_number
     *
     * @param int|null $installment_number Indicates the payment number (useful in the case of an order comprising payments with installments)
     *
     * @return self
     */
    public function setInstallmentNumber($installment_number)
    {
        if (is_null($installment_number)) {
            array_push($this->openAPINullablesSetToNull, 'installment_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('installment_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['installment_number'] = $installment_number;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentState|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentState|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets meta
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsCommonMetaModel|null
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsCommonMetaModel|null $meta meta
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets payment_off_line_mean
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans|null
     */
    public function getPaymentOffLineMean()
    {
        return $this->container['payment_off_line_mean'];
    }

    /**
     * Sets payment_off_line_mean
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsEnumsPaymentMeans|null $payment_off_line_mean payment_off_line_mean
     *
     * @return self
     */
    public function setPaymentOffLineMean($payment_off_line_mean)
    {
        if (is_null($payment_off_line_mean)) {
            throw new \InvalidArgumentException('non-nullable payment_off_line_mean cannot be null');
        }
        $this->container['payment_off_line_mean'] = $payment_off_line_mean;

        return $this;
    }

    /**
     * Gets refund_operations
     *
     * @return \OpenAPI\Client\Model\HelloAssoApiV5ModelsStatisticsRefundOperationLightModel[]|null
     */
    public function getRefundOperations()
    {
        return $this->container['refund_operations'];
    }

    /**
     * Sets refund_operations
     *
     * @param \OpenAPI\Client\Model\HelloAssoApiV5ModelsStatisticsRefundOperationLightModel[]|null $refund_operations The refund operations information for the specific payment.
     *
     * @return self
     */
    public function setRefundOperations($refund_operations)
    {
        if (is_null($refund_operations)) {
            array_push($this->openAPINullablesSetToNull, 'refund_operations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('refund_operations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['refund_operations'] = $refund_operations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


