<?php
/**
 * HelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfigurationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HelloAsso API
 *
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description HelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfiguration
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfigurationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfiguration"
     */
    public function testHelloAssoCoreAccountsTaxReceiptsOrganizationFiscalReceiptOptionsConfiguration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cerfa_type_id"
     */
    public function testPropertyCerfaTypeId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "jo_category_id"
     */
    public function testPropertyJoCategoryId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "format_option_model"
     */
    public function testPropertyFormatOptionModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signatory_model"
     */
    public function testPropertySignatoryModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address_model"
     */
    public function testPropertyAddressModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
