<?php
/**
 * FormulairesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HelloAsso API
 *
 * HelloAsso Open Api specification
 *
 * The version of the OpenAPI document: public
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FormulairesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormulairesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsOrganizationSlugFormTypesGet
     *
     * Obtenir une liste des types de formulaires pour une organisation.
     *
     */
    public function testOrganizationsOrganizationSlugFormTypesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsOrganizationSlugFormsFormTypeActionQuickCreatePost
     *
     * Créer un événement simplifié pour un organisme.
     *
     */
    public function testOrganizationsOrganizationSlugFormsFormTypeActionQuickCreatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsOrganizationSlugFormsFormTypeFormSlugPublicGet
     *
     * Obtenir des données publiques détaillées sur un formulaire.
     *
     */
    public function testOrganizationsOrganizationSlugFormsFormTypeFormSlugPublicGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsOrganizationSlugFormsGet
     *
     * Obtenir les formulaires d'une organisation.
     *
     */
    public function testOrganizationsOrganizationSlugFormsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
